In [1]:
from network import PPONetwork
%load_ext autoreload
%autoreload 2
import numpy  as np
import torch
from torch import nn

In [7]:
nnet = PPONetwork(2, 4)
nnet = nnet.double()

In [12]:
x = np.array([1,2,3,4], dtype=np.float)
xs = np.random.randn(10,4)

In [11]:
nnet(x)

Mean : tensor([ 0.2075, -0.2327], dtype=torch.float64, grad_fn=<ThAddBackward>) torch.Size([2])
Std :  tensor([-0.6931], dtype=torch.float64, grad_fn=<ThAddBackward>) torch.Size([1])


(tensor([ 0.2075, -0.2327], dtype=torch.float64, grad_fn=<ThAddBackward>),
 tensor([0.5000], dtype=torch.float64, grad_fn=<ExpBackward>),
 tensor([-0.2355], dtype=torch.float64, grad_fn=<ThAddBackward>))

In [49]:
xs = torch.tensor(xs, dtype = torch.double)
means, std, value  = nnet(xs)

Mean : tensor([[-0.0224,  0.1146],
        [ 0.0917, -0.1129],
        [ 0.1191, -0.0860],
        [ 0.0513,  0.0951],
        [ 0.0921,  0.0053],
        [ 0.0679,  0.0641],
        [ 0.0044, -0.1068],
        [ 0.1797, -0.1173],
        [ 0.0017,  0.1411],
        [ 0.0538,  0.0494]], dtype=torch.float64, grad_fn=<ThAddmmBackward>) torch.Size([10, 2])
Std :  tensor([-0.6931], dtype=torch.float64, grad_fn=<ThAddBackward>) torch.Size([1])


In [56]:
print(xs[0])
nnet.get_action(xs[0])

tensor([ 0.4545,  0.3455, -0.8472, -1.2102], dtype=torch.float64)
Mean : tensor([-0.0224,  0.1146], dtype=torch.float64) torch.Size([2])
Std :  tensor([-0.6931], dtype=torch.float64) torch.Size([1])
Exp Sttd :  tensor([0.5000], dtype=torch.float64) torch.Size([1])


([-0.5748924518900584, 0.0517523366561395],
 -1.45397586665041,
 -0.15552738692353435)

In [55]:
sample = torch.rand([10,2], dtype = torch.float)

In [34]:
print(sample)
sample[:,0]



tensor([[0.8355, 0.5562],
        [0.7152, 0.3174],
        [0.8029, 0.8213],
        [0.2056, 0.9553],
        [0.8065, 0.1839],
        [0.0385, 0.4929],
        [0.3693, 0.7652],
        [0.7357, 0.1426],
        [0.8311, 0.1436],
        [0.1331, 0.6377]])


tensor([0.8355, 0.7152, 0.8029, 0.2056, 0.8065, 0.0385, 0.3693, 0.7357, 0.8311,
        0.1331])

In [36]:
from torch.distributions.multivariate_normal import MultivariateNormal


In [43]:
dist = MultivariateNormal(sample[:,0], 4*torch.eye(10))
dist.sample()
dist.log_prob(dist.sample())

tensor(-18.7749)

In [39]:
torch.eye(3)*3

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [45]:
dist = MultivariateNormal(sample, 2*torch.eye(2))

In [48]:
dist.log_prob(dist.sample())

tensor([-4.9777, -5.5855, -2.9417, -4.2581, -2.9070, -2.6100, -3.6743, -2.9898,
        -2.5913, -3.4028])

In [59]:
action = np.array([1,3,65,6])

In [60]:
action = np.tanh(action)


In [62]:
print(action)

[0.76159416 0.99505475 1.         0.99998771]


In [63]:
action*100




array([ 76.1594156 ,  99.50547537, 100.        ,  99.99877117])

In [144]:
from network import  PPONetwork2

In [145]:

net = PPONetwork2(action_count = 2, in_size=4)
net = net.double()

In [146]:
data = torch.randn([10,4],dtype = torch.double)
data2 = torch.randn([1,4],dtype = torch.double)
data3 =  torch.randn([4],dtype = torch.double)

In [147]:
len(data.shape)

2

In [148]:
mean, std,  value = net(data)
mean.shape


Mean : tensor([[0.1300, 0.0562],
        [0.1574, 0.1561],
        [0.0834, 0.0757],
        [0.0238, 0.0720],
        [0.1089, 0.0055],
        [0.0512, 0.1085],
        [0.1246, 0.0925],
        [0.0757, 0.0441],
        [0.0768, 0.0223],
        [0.1399, 0.1802]], dtype=torch.float64, grad_fn=<SliceBackward>) torch.Size([10, 2])
Std :  tensor([[ 0.2339,  0.1057],
        [ 0.3744,  0.0188],
        [ 0.1322,  0.0288],
        [ 0.0923,  0.0673],
        [ 0.4505,  0.1652],
        [ 0.1135, -0.0308],
        [ 0.1488,  0.0659],
        [ 0.0754,  0.0432],
        [ 0.0763,  0.0383],
        [ 0.2392, -0.0453]], dtype=torch.float64, grad_fn=<SliceBackward>) torch.Size([10, 2])


torch.Size([10, 2])

In [159]:
print("Value : ",net.get_action(data1))

NameError: name 'data1' is not defined

In [52]:
mean, std,  value = net(data2)
mean.shape

Mean : tensor([[-0.0174, -0.0159]], dtype=torch.float64, grad_fn=<SliceBackward>) torch.Size([1, 2])
Std :  tensor([[ 0.0888, -0.1516]], dtype=torch.float64, grad_fn=<SliceBackward>) torch.Size([1, 2])


torch.Size([1, 2])

In [53]:
mean, std,  value = net(data3)
mean.shape

Mean : tensor([[0.0344, 0.0758]], dtype=torch.float64, grad_fn=<SliceBackward>) torch.Size([1, 2])
Std :  tensor([[ 0.0952, -0.0544]], dtype=torch.float64, grad_fn=<SliceBackward>) torch.Size([1, 2])


torch.Size([1, 2])

In [68]:
[s*torch.eye(2, dtype = torch.double) for s in std]


[tensor([[1.0023, 0.0000],
         [0.0000, 0.8570]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[0.9804, 0.0000],
         [0.0000, 0.8959]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.1126, 0.0000],
         [0.0000, 0.8953]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.1415, 0.0000],
         [0.0000, 0.8344]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.0830, 0.0000],
         [0.0000, 0.8659]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.2329, 0.0000],
         [0.0000, 0.9183]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.0978, 0.0000],
         [0.0000, 0.9476]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.0699, 0.0000],
         [0.0000, 0.8541]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.1185, 0.0000],
         [0.0000, 0.9307]], dtype=torch.float64, grad_fn=<ThMulBackward>),
 tensor([[1.0840, 0.0000],
         [0.0000, 0.8663]], dtype=torch.float64, grad_f

In [66]:
std*torch.eye(2)

RuntimeError: The size of tensor a (10) must match the size of tensor b (2) at non-singleton dimension 0

In [75]:
std = std.view([-1,1,2])

In [81]:
torch.matmul(std,torch.eye(2, dtyep = torch.double ))

TypeError: eye() received an invalid combination of arguments - got (int, dtyep=torch.dtype), but expected one of:
 * (int n, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)
 * (int n, int m, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)


In [119]:
mean, std,  value = net(data)
a = torch.eye(2, dtype = torch.double)
a.unsqueeze_(0)
a = a.expand(10, 2,2)
# a = a.transpose(2, 0)
print(a)
print(a.shape)

tensor([[[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]],

        [[1., 0.],
         [0., 1.]]], dtype=torch.float64)
torch.Size([10, 2, 2])


In [135]:
print(std.shape)
print(torch.unsqueeze(std, 1).shape)
print(a.shape)

torch.Size([10, 2])
torch.Size([10, 1, 2])
torch.Size([10, 2, 2])


In [140]:
print((torch.unsqueeze(std, 1)*a).shape)


torch.Size([10, 2, 2])


In [128]:
stds =  [s*a for s, a in  zip(std, a)]


ValueError: only one element tensors can be converted to Python scalars